version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    steps:
      # get code
      - checkout
      # get dependencies from cache or download
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "backend/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-cache
      - run:
          name: Install dependencies
          command: npm i
          working_directory: backend
      # run tests
      - run:
          name: Run tests with code coverage
          command: npm test --coverage
          working_directory: backend
      # save workspace
      - persist_to_workspace:
          root: backend
          paths:
            - .
      # save cache
      - save_cache:
          paths:
            - backend/node_modules
          key: dependencies-cache-{{ checksum "backend/package.json" }}

  deploy-test:
    docker:
      - image: circleci/node:8.10
    steps:
      # load workspace
      - attach_workspace:
          at: .
      # deploy to test
      - run:
          name: Deploy application
          command: npm run deploy-test

  deploy-production:
    docker:
      - image: circleci/node:8.10
    steps:
      # load workspace
      - attach_workspace:
          at: .
      # deploy to production
      - run:
          name: Deploy application
          command: npm run deploy-production

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - test
                - master

      - deploy-test:
          requires:
            - build
          filters:
            branches:
              only: test

      - hold:
          type: approval
          requires:
           - build
          filters:
            branches:
              only: master

      - deploy-production:
          requires:
            - hold
          filters:
            branches:
              only: master
