version: 2
jobs:
  build:
    working_directory: ~/hello-world-ci # TODO: change
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-cache
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install
      # run tests
      - run: 
          name: Run tests with code coverage
          command: npm test --coverage
      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}

  deploy-test:
    working_directory: ~/hello-world-ci # TODO: change
    docker:
      - image: circleci/node:8.10
    steps:
      # deploy app
      - run:
          name: Deploy application
          command: npm run deploy-test

  deploy-production:
    working_directory: ~/hello-world-ci # TODO: change
    docker:
      - image: circleci/node:8.10
    steps:
      # deploy app
      - run:
          name: Deploy application
          command: npm run deploy-production

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - test
                - master

      - deploy-test:
          requires:
            - build
          filters:
            branches:
              only: test

      - hold:
          type: approval
          requires:
           - build

      - deploy-production:
          requires:
            - hold
          filters:
            branches:
              only: master
