version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.0

jobs:
  build:
    docker:
      - image: circleci/node:8.10
    environment:
      AWS_REGION: us-east-1
    steps:
      # get code
      - checkout
      - run:
          name: Set AWS variable
          command: export AWS_ACCESS_KEY_ID="test"
      - run:
          name: Set AWS variable
          command: export AWS_SECRET_ACCESS_KEY="test"
      # put aws credentials to the file
      - run:
          name: Put aws credentials
          command: mkdir ~/.aws && echo -e "[sweepy-prod]\naws_access_key_id=$AWS_ACCESS_KEY_ID\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY\n\n[sweepy-deploy-prod]\naws_access_key_id=$AWS_ACCESS_KEY_ID\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY\n" > ~/.aws/credentials
      # install AWS CLI dependencies
      - run:
          name: Install PIP
          command: sudo apt-get install python-pip python-dev
      - run:
          name: Install AWS CLI
          command: sudo pip install awscli
      - run:
          name: check AWS region variable
          command: echo $AWS_REGION
      # put extension output to S3
      - aws-s3/copy:
          from: 'chrome-extension/output'
          to: 's3://ci-sweepy-chrome-extension-output'
